"use client";
import { useCallback, useEffect, useState } from "react";
import type { User } from "firebase/auth";
import type { UserProfile } from "@/lib/types";
import { FiRefreshCw, FiTrash2, FiUserPlus } from "react-icons/fi";

type ListedUser=UserProfile&{uid:string};
export default function AdminPanel({user}:{user:User}){
 const [users,setUsers]=useState<ListedUser[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [form,setForm]=useState({nim:"",name:"",password:"",role:"student"});
 const request=useCallback(async(method:string,body?:unknown)=>{const token=await user.getIdToken();const res=await fetch("/api/admin/users",{method,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const json=await res.json();if(!res.ok)throw new Error(json.error||"Permintaan gagal");return json},[user]);
 const load=useCallback(async()=>{try{setUsers((await request("GET")).users)}catch(e){setError(e instanceof Error?e.message:"Gagal memuat")}},[request]);useEffect(()=>{load()},[load]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await request("POST",form);setForm({nim:"",name:"",password:"",role:"student"});await load()}catch(e){setError(e instanceof Error?e.message:"Gagal membuat akun")}finally{setBusy(false)}};
 const patch=async(uid:string,changes:object)=>{try{await request("PATCH",{uid,...changes});await load()}catch(e){setError(e instanceof Error?e.message:"Gagal memperbarui")}};
 const remove=async(u:ListedUser)=>{if(!confirm(`Hapus akun ${u.nim} beserta data akademiknya?`))return;try{await request("DELETE",{uid:u.uid});await load()}catch(e){setError(e instanceof Error?e.message:"Gagal menghapus")}};
 return <section className="stack"><div className="card"><div className="flex between"><div><h2 style={{margin:0}}>Manajemen Mahasiswa</h2><p className="muted">Daftarkan NIM sebelum mahasiswa dapat masuk.</p></div><button className="btn ghost" onClick={load}><FiRefreshCw/> Muat ulang</button></div><form className="admin-form" onSubmit={create}><label>NIM<input required value={form.nim} onChange={e=>setForm({...form,nim:e.target.value})}/></label><label>Nama<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Password awal<input required minLength={6} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="student">Mahasiswa</option><option value="admin">Admin</option></select></label><button disabled={busy} className="btn primary"><FiUserPlus/> Tambah</button></form>{error&&<p className="error">{error}</p>}</div><div className="card table-wrap"><table className="admin-table"><thead><tr><th>NIM</th><th>Nama</th><th>Role</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{users.map(u=><tr key={u.uid}><td>{u.nim}</td><td>{u.name}</td><td><select value={u.role} onChange={e=>patch(u.uid,{role:e.target.value})}><option value="student">Mahasiswa</option><option value="admin">Admin</option></select></td><td><button className={`btn ${u.active?"primary":"danger"}`} onClick={()=>patch(u.uid,{active:!u.active})}>{u.active?"Aktif":"Nonaktif"}</button></td><td><div className="flex"><button className="btn ghost" onClick={()=>{const password=prompt("Password baru (minimal 6 karakter):");if(password)patch(u.uid,{password})}}>Ubah password</button><button aria-label="Hapus akun" className="btn danger icon" onClick={()=>remove(u)}><FiTrash2/></button></div></td></tr>)}</tbody></table></div></section>
}
