"use client";
import { useEffect, useMemo, useState } from "react";
import { doc, getDoc } from "firebase/firestore";
import { Bar, Doughnut, Radar } from "react-chartjs-2";
import { Chart as ChartJS, ArcElement, BarElement, CategoryScale, Filler, Legend, LinearScale, LineElement, PointElement, RadialLinearScale, Tooltip } from "chart.js";
import { db } from "@/lib/firebase";
import { gradeScale } from "@/lib/calculations";
import type { AcademicData, Course, Curriculum, CurriculumCourse } from "@/lib/types";
import { FiAward, FiBookOpen, FiCheckCircle, FiInfo } from "react-icons/fi";

ChartJS.register(ArcElement,BarElement,CategoryScale,Filler,Legend,LinearScale,LineElement,PointElement,RadialLinearScale,Tooltip);
const norm=(s:string)=>s.toLowerCase().replace(/praktikum|praktek|prakitikum/g,"").replace(/[^a-z0-9]/g,"");
const tokens=(s:string)=>new Set(s.toLowerCase().replace(/praktikum|praktek|prakitikum/g,"").split(/[^a-z0-9]+/).filter(x=>x.length>2));
const similarity=(a:string,b:string)=>{const x=tokens(a),y=tokens(b);if(!x.size||!y.size)return 0;let common=0;x.forEach(t=>{if(y.has(t))common++});return common/Math.max(x.size,y.size)};
const matchCourse=(name:string,courses:CurriculumCourse[])=>{const exact=courses.find(c=>norm(c.name)===norm(name));if(exact)return exact;const ranked=courses.map(c=>({c,score:similarity(name,c.name)})).sort((a,b)=>b.score-a.score);return ranked[0]?.score>=.5?ranked[0].c:undefined};
const level=(score:number)=>score>=85?"Unggul":score>=70?"Tercapai":score>=60?"Perlu penguatan":"Belum tercapai";
type Evidence={course:Course;curriculum:CurriculumCourse;score:number};

export default function CplDashboard({uid,theme}:{uid:string;theme:string}){
 const [curriculum,setCurriculum]=useState<Curriculum|null>(null),[planner,setPlanner]=useState<AcademicData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{Promise.all([getDoc(doc(db,"curricula","teknik-elektro")),getDoc(doc(db,"academicData",uid))]).then(([c,p])=>{if(c.exists())setCurriculum(c.data() as Curriculum);if(p.exists())setPlanner(p.data() as AcademicData);setLoading(false)}).catch(e=>{setError(e?.code==="permission-denied"?"Akses Firestore ditolak. Publikasikan rules curricula terlebih dahulu.":"Data CPL tidak dapat dimuat.");setLoading(false)})},[uid]);
 const latestCourses=useMemo(()=>{const map=new Map<string,Course>();(planner?.semesters||[]).forEach(s=>s.courses.forEach(c=>{if(c.name.trim()&&Number(c.sks)>0)map.set(norm(c.name),c)}));return [...map.values()]},[planner]);
 const evidence=useMemo<Evidence[]>(()=>{if(!curriculum)return[];return latestCourses.flatMap(course=>{const matched=matchCourse(course.name,curriculum.courses);return matched?.cplCodes?.length?[{course,curriculum:matched,score:gradeScale[course.grade]/4*100}]:[]})},[latestCourses,curriculum]);
 const unmatched=useMemo(()=>curriculum?latestCourses.filter(c=>!matchCourse(c.name,curriculum.courses)?.cplCodes?.length):[],[latestCourses,curriculum]);
 const results=useMemo(()=>curriculum?.cpls.map(c=>{const rows=evidence.filter(e=>e.curriculum.cplCodes.includes(c.code));const weight=rows.reduce((s,e)=>s+Number(e.course.sks),0);const value=weight?rows.reduce((s,e)=>s+e.score*Number(e.course.sks),0)/weight:0;return {...c,value,count:rows.length,status:level(value)}})||[],[curriculum,evidence]);
 const measured=results.filter(r=>r.count),average=measured.length?measured.reduce((s,r)=>s+r.value,0)/measured.length:0,target=curriculum?.target||70,achieved=measured.filter(r=>r.value>=target).length;
 const profileResults=useMemo(()=>curriculum?.profiles.map(p=>{const rows=results.filter(r=>r.count&&r.profileCodes.includes(p.code));return {...p,value:rows.length?rows.reduce((s,r)=>s+r.value,0)/rows.length:0,count:rows.length}})||[],[curriculum,results]);
 const dominant=[...profileResults].filter(x=>x.count).sort((a,b)=>b.value-a.value)[0],color=theme==="light"?"#64748b":"#cbd5e1";
 if(loading)return <div className="card">Menghitung capaian CPL...</div>;
 if(error)return <div className="card"><h2>Data CPL belum dapat dibuka</h2><p className="error">{error}</p></div>;
 if(!curriculum)return <div className="card"><h2>Kurikulum belum tersedia</h2><p className="muted">Admin perlu mengimpor workbook Teknik Elektro.</p></div>;
 return <div className="stack cpl-page">
  <div className="cpl-hero"><div><span className="badge">{curriculum.programCode}</span><h2>Capaian Pembelajaran Lulusan</h2><p>Otomatis dari nilai mata kuliah · {curriculum.programName}</p></div><div className="hero-score"><strong>{average.toFixed(1)}</strong><span>Rata-rata CPL</span></div></div>
  <div className="stats-bar"><Metric label="Matkul Terhubung" value={`${evidence.length}/${latestCourses.length}`}/><Metric label="CPL Terukur" value={`${measured.length}/${results.length}`}/><Metric label="CPL Tercapai" value={`${achieved}/${measured.length||0}`} color="var(--success)"/><Metric label="Target Minimum" value={`${target}%`} color="var(--accent)"/></div>
  <div className="card auto-info"><FiInfo/><div><strong>Perhitungan otomatis</strong><p>Nilai huruf dikonversi dari bobot akademik ke skala 100, lalu dirata-ratakan berdasarkan SKS pada setiap CPL yang dipetakan di workbook. Tidak perlu mengisi nilai CPMK manual.</p></div></div>
  <div className="cpl-grid"><div className="card chart-card"><h3>Radar Ketercapaian CPL</h3><Radar data={{labels:results.map(r=>r.code),datasets:[{label:"Capaian",data:results.map(r=>r.value),backgroundColor:"rgba(99,102,241,.22)",borderColor:"#6366f1"},{label:"Target",data:results.map(()=>target),borderColor:"#ef4444",borderDash:[5,5],pointRadius:0}]}} options={{maintainAspectRatio:false,scales:{r:{min:0,max:100,ticks:{display:false},grid:{color:"#64748b44"},angleLines:{color:"#64748b44"},pointLabels:{color}}}}}/></div><div className="card chart-card"><h3>Nilai per CPL</h3><Bar data={{labels:results.map(r=>r.code),datasets:[{label:"Nilai CPL",data:results.map(r=>r.value),backgroundColor:results.map(r=>r.value>=target?"#10b981":"#ef4444")}]}} options={{maintainAspectRatio:false,scales:{y:{min:0,max:100,ticks:{color},grid:{color:"#64748b33"}},x:{ticks:{color},grid:{display:false}}}}}/></div></div>
  <div className="cpl-grid"><div className="card"><div className="character"><FiAward/><div><span className="muted">Karakter lulusan dominan</span><h3>{dominant?.title||"Belum dapat disimpulkan"}</h3><p>{dominant?.description||"Masukkan mata kuliah dan nilai di Planner agar profil lulusan terbentuk."}</p></div>{dominant&&<strong>{dominant.value.toFixed(1)}%</strong>}</div><div className="profile-list">{profileResults.map(p=><div key={p.code}><span>{p.code} · {p.title}</span><div className="progress"><i style={{width:`${p.value}%`}}/></div><b>{p.count?p.value.toFixed(1):"–"}</b></div>)}</div></div><div className="card chart-card"><h3>Tingkat Keberhasilan CPL</h3><Doughnut data={{labels:["Tercapai","Belum"],datasets:[{data:[achieved,Math.max(0,measured.length-achieved)],backgroundColor:["#10b981","#334155"],borderWidth:0}]}} options={{maintainAspectRatio:false,cutout:"72%",plugins:{legend:{labels:{color}}}}}/></div></div>
  <div className="card table-wrap"><h3>Kontribusi Mata Kuliah</h3><table><thead><tr><th>Mata Kuliah Planner</th><th>Nilai</th><th>Skala CPL</th><th>CPL yang Dibentuk</th></tr></thead><tbody>{evidence.map(e=><tr key={`${e.course.name}-${e.course.grade}`}><td><FiCheckCircle color="var(--success)"/> {e.course.name}<small>Terhubung ke: {e.curriculum.name}</small></td><td><strong>{e.course.grade}</strong></td><td>{e.score.toFixed(1)}</td><td>{e.curriculum.cplCodes.join(", ")}</td></tr>)}</tbody></table>{!evidence.length&&<p className="muted">Belum ada mata kuliah Planner yang cocok dengan kurikulum Teknik Elektro.</p>}</div>
  {unmatched.length>0&&<div className="card unmatched"><h3><FiBookOpen/> Mata kuliah belum terhubung</h3><p className="muted">Gunakan nama resmi kurikulum agar pemetaan otomatis ditemukan.</p><div className="chips">{unmatched.map(c=><span key={c.name}>{c.name}</span>)}</div></div>}
  <div className="card table-wrap"><h3>Rincian CPL</h3><table><thead><tr><th>CPL</th><th>Karakter/Keyword</th><th>Matkul</th><th>Nilai</th><th>Status</th></tr></thead><tbody>{results.map(r=><tr key={r.code}><td><strong>{r.code}</strong><small>{r.description}</small></td><td>{r.keyword}</td><td>{r.count}</td><td>{r.count?r.value.toFixed(2):"–"}</td><td><span className={`status ${r.count&&r.value>=target?"ok":"low"}`}>{r.count?r.status:"Belum ada data"}</span></td></tr>)}</tbody></table></div>
 </div>;
}
function Metric({label,value,color}:{label:string;value:string|number;color?:string}){return <div className="stat-box"><div className="stat-label">{label}</div><div className="stat-val" style={{color}}>{value}</div></div>}
