"use client";
import { useEffect, useMemo, useState } from "react";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { Bar, Doughnut, Radar } from "react-chartjs-2";
import { Chart as ChartJS, ArcElement, BarElement, CategoryScale, Filler, Legend, LinearScale, LineElement, PointElement, RadialLinearScale, Tooltip } from "chart.js";
import { db } from "@/lib/firebase";
import type { AcademicData, CplAssessment, Curriculum } from "@/lib/types";
import { FiAward, FiPlus, FiTrash2 } from "react-icons/fi";
ChartJS.register(ArcElement,BarElement,CategoryScale,Filler,Legend,LinearScale,LineElement,PointElement,RadialLinearScale,Tooltip);
const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]/g,"");
const level=(score:number)=>score>=85?"Unggul":score>=70?"Tercapai":score>=60?"Perlu penguatan":"Belum tercapai";

export default function CplDashboard({uid,theme}:{uid:string;theme:string}){
 const [curriculum,setCurriculum]=useState<Curriculum|null>(null),[assessments,setAssessments]=useState<CplAssessment[]>([]),[planner,setPlanner]=useState<AcademicData|null>(null),[loading,setLoading]=useState(true),[course,setCourse]=useState(""),[cpmk,setCpmk]=useState(""),[score,setScore]=useState("");
 useEffect(()=>{Promise.all([getDoc(doc(db,"curricula","teknik-elektro")),getDoc(doc(db,"cplAssessments",uid)),getDoc(doc(db,"academicData",uid))]).then(([c,a,p])=>{if(c.exists())setCurriculum(c.data() as Curriculum);if(a.exists())setAssessments((a.data().items||[]) as CplAssessment[]);if(p.exists())setPlanner(p.data() as AcademicData);setLoading(false)}).catch(()=>setLoading(false))},[uid]);
 const enteredNames=useMemo(()=>new Set((planner?.semesters||[]).flatMap(s=>s.courses.filter(c=>c.name.trim()).map(c=>norm(c.name)))),[planner]);
 const courses=useMemo(()=>{if(!curriculum)return[];return [...curriculum.courses].sort((a,b)=>Number(enteredNames.has(norm(b.name)))-Number(enteredNames.has(norm(a.name)))||a.name.localeCompare(b.name))},[curriculum,enteredNames]);
 const availableCpmks=useMemo(()=>{if(!curriculum||!course)return[];const n=norm(course);const exact=curriculum.cpmks.filter(c=>norm(c.course).includes(n)||n.includes(norm(c.course)));if(exact.length)return exact;const mapped=curriculum.courses.find(c=>c.name===course)?.cplCodes||[];return curriculum.cpmks.filter(c=>mapped.includes(c.cplCode)).slice(0,30)},[curriculum,course]);
 useEffect(()=>setCpmk(availableCpmks[0]?.code||""),[course,availableCpmks]);
 const save=async(items:CplAssessment[])=>{setAssessments(items);await setDoc(doc(db,"cplAssessments",uid),{programId:"teknik-elektro",items,updatedAt:new Date()})};
 const add=async(e:React.FormEvent)=>{e.preventDefault();const item=availableCpmks.find(x=>x.code===cpmk),value=Number(score);if(!item||value<0||value>100)return;const sem=curriculum?.courses.find(x=>x.name===course)?.semester||0;await save([...assessments.filter(x=>!(x.course===course&&x.cpmkCode===cpmk)),{id:crypto.randomUUID(),course,cpmkCode:cpmk,cplCode:item.cplCode,score:value,cohort:new Date().getFullYear().toString(),semester:sem}]);setScore("")};
 const results=useMemo(()=>curriculum?.cpls.map(c=>{const rows=assessments.filter(a=>a.cplCode===c.code);const value=rows.length?rows.reduce((s,a)=>s+a.score,0)/rows.length:0;return {...c,value,count:rows.length,status:level(value)}})||[],[curriculum,assessments]);
 const measured=results.filter(r=>r.count),average=measured.length?measured.reduce((s,r)=>s+r.value,0)/measured.length:0,target=curriculum?.target||70,achieved=measured.filter(r=>r.value>=target).length;
 const profileResults=useMemo(()=>curriculum?.profiles.map(p=>{const rows=results.filter(r=>r.count&&r.profileCodes.includes(p.code));return {...p,value:rows.length?rows.reduce((s,r)=>s+r.value,0)/rows.length:0,count:rows.length}})||[],[curriculum,results]);
 const dominant=[...profileResults].filter(x=>x.count).sort((a,b)=>b.value-a.value)[0];const color=theme==="light"?"#64748b":"#cbd5e1";
 if(loading)return <div className="card">Memuat kurikulum CPL...</div>;
 if(!curriculum)return <div className="card"><h2>Kurikulum belum tersedia</h2><p className="muted">Admin perlu menjalankan import workbook Teknik Elektro terlebih dahulu.</p></div>;
 return <div className="stack cpl-page"><div className="cpl-hero"><div><span className="badge">{curriculum.programCode}</span><h2>Capaian Pembelajaran Lulusan</h2><p>{curriculum.programName} · target ketercapaian {target}%</p></div><div className="hero-score"><strong>{average.toFixed(1)}</strong><span>Rata-rata CPL</span></div></div>
 <div className="stats-bar"><Metric label="CPL Terukur" value={`${measured.length}/${results.length}`}/><Metric label="CPL Tercapai" value={`${achieved}/${measured.length||0}`} color="var(--success)"/><Metric label="CPMK Dinilai" value={assessments.length}/><Metric label="Target Minimum" value={`${target}%`} color="var(--accent)"/></div>
 <div className="cpl-grid"><div className="card"><h3>Input Nilai CPMK</h3><p className="muted">Mata kuliah yang sudah dimasukkan di planner ditampilkan lebih dahulu.</p><form className="score-form" onSubmit={add}><label>Mata Kuliah<select required value={course} onChange={e=>setCourse(e.target.value)}><option value="">Pilih mata kuliah</option>{courses.map(c=><option key={c.name} value={c.name}>{enteredNames.has(norm(c.name))?"✓ ":""}{c.name}</option>)}</select></label><label>CPMK<select required value={cpmk} onChange={e=>setCpmk(e.target.value)}><option value="">Pilih CPMK</option>{availableCpmks.map(c=><option key={`${c.code}-${c.description}`} value={c.code}>{c.code} · {c.cplCode}</option>)}</select></label>{availableCpmks.find(x=>x.code===cpmk)&&<p className="cpmk-desc">{availableCpmks.find(x=>x.code===cpmk)?.description}</p>}<label>Nilai CPMK (0–100)<input required type="number" min="0" max="100" step="0.01" value={score} onChange={e=>setScore(e.target.value)}/></label><button className="btn primary"><FiPlus/> Simpan Nilai</button></form></div>
 <div className="card chart-card"><h3>Radar Ketercapaian CPL</h3><Radar data={{labels:results.map(r=>r.code),datasets:[{label:"Capaian",data:results.map(r=>r.value),backgroundColor:"rgba(99,102,241,.22)",borderColor:"#6366f1"},{label:"Target",data:results.map(()=>target),borderColor:"#ef4444",borderDash:[5,5],pointRadius:0}]}} options={{maintainAspectRatio:false,scales:{r:{min:0,max:100,ticks:{display:false},grid:{color:"#64748b44"},angleLines:{color:"#64748b44"},pointLabels:{color}}}}}/></div></div>
 <div className="cpl-grid"><div className="card chart-card"><h3>Nilai per CPL</h3><Bar data={{labels:results.map(r=>r.code),datasets:[{label:"Nilai CPL",data:results.map(r=>r.value),backgroundColor:results.map(r=>r.value>=target?"#10b981":"#ef4444")} ]}} options={{maintainAspectRatio:false,scales:{y:{min:0,max:100,ticks:{color},grid:{color:"#64748b33"}},x:{ticks:{color},grid:{display:false}}}}}/></div><div className="card chart-card"><h3>Tingkat Keberhasilan</h3><Doughnut data={{labels:["Tercapai","Belum"],datasets:[{data:[achieved,Math.max(0,measured.length-achieved)],backgroundColor:["#10b981","#334155"],borderWidth:0}]}} options={{maintainAspectRatio:false,cutout:"72%",plugins:{legend:{labels:{color}}}}}/></div></div>
 <div className="card"><div className="character"><FiAward/><div><span className="muted">Karakter lulusan dominan</span><h3>{dominant?.title||"Belum dapat disimpulkan"}</h3><p>{dominant?.description||"Masukkan nilai CPMK agar sistem dapat membentuk profil capaian lulusan."}</p></div>{dominant&&<strong>{dominant.value.toFixed(1)}%</strong>}</div><div className="profile-list">{profileResults.map(p=><div key={p.code}><span>{p.code} · {p.title}</span><div className="progress"><i style={{width:`${p.value}%`}}/></div><b>{p.count?p.value.toFixed(1):"–"}</b></div>)}</div></div>
 <div className="card table-wrap"><h3>Rincian CPL</h3><table><thead><tr><th>CPL</th><th>Karakter/Keyword</th><th>CPMK Dinilai</th><th>Nilai</th><th>Status</th></tr></thead><tbody>{results.map(r=><tr key={r.code}><td><strong>{r.code}</strong><small>{r.description}</small></td><td>{r.keyword}</td><td>{r.count}</td><td>{r.count?r.value.toFixed(2):"–"}</td><td><span className={`status ${r.count&&r.value>=target?"ok":"low"}`}>{r.count?r.status:"Belum ada data"}</span></td></tr>)}</tbody></table></div>
 <div className="card table-wrap"><h3>Nilai CPMK Tersimpan</h3><table><thead><tr><th>Mata Kuliah</th><th>CPMK</th><th>CPL</th><th>Nilai</th><th/></tr></thead><tbody>{assessments.map(a=><tr key={a.id}><td>{a.course}</td><td>{a.cpmkCode}</td><td>{a.cplCode}</td><td>{a.score}</td><td><button className="btn danger icon" onClick={()=>save(assessments.filter(x=>x.id!==a.id))}><FiTrash2/></button></td></tr>)}</tbody></table></div></div>
}
function Metric({label,value,color}:{label:string;value:string|number;color?:string}){return <div className="stat-box"><div className="stat-label">{label}</div><div className="stat-val" style={{color}}>{value}</div></div>}
