import { NextRequest, NextResponse } from "next/server";
import { adminAuth, adminDb } from "@/lib/firebase-admin";

async function authorize(req:NextRequest){
 const header=req.headers.get("authorization");if(!header?.startsWith("Bearer "))throw new Error("UNAUTHORIZED");
 const decoded=await adminAuth().verifyIdToken(header.slice(7));const profile=await adminDb().collection("users").doc(decoded.uid).get();
 if(!profile.exists||profile.data()?.role!=="admin"||profile.data()?.active!==true)throw new Error("FORBIDDEN");return decoded.uid;
}
const fail=(e:unknown)=>{const msg=e instanceof Error?e.message:"Terjadi kesalahan";const status=msg==="UNAUTHORIZED"?401:msg==="FORBIDDEN"?403:400;return NextResponse.json({error:msg.replace("UNAUTHORIZED","Sesi tidak valid").replace("FORBIDDEN","Akses admin diperlukan")},{status})};
export async function GET(req:NextRequest){try{await authorize(req);const snap=await adminDb().collection("users").orderBy("nim").get();return NextResponse.json({users:snap.docs.map(d=>({uid:d.id,...d.data()}))})}catch(e){return fail(e)}}
export async function POST(req:NextRequest){try{await authorize(req);const {nim,name,password,role}=await req.json();const clean=String(nim||"").trim().toLowerCase();if(!clean||!name||!password||password.length<6)throw new Error("Data akun belum valid");if(!/^[a-z0-9._-]+$/.test(clean))throw new Error("Format NIM tidak valid");const account=await adminAuth().createUser({email:`${clean}@student.ipk.local`,password,displayName:String(name),disabled:false});await adminDb().collection("users").doc(account.uid).set({nim:clean,name:String(name).trim(),role:role==="admin"?"admin":"student",active:true,createdAt:new Date()});return NextResponse.json({uid:account.uid},{status:201})}catch(e){return fail(e)}}
export async function PATCH(req:NextRequest){try{const actor=await authorize(req);const {uid,password,...changes}=await req.json();if(!uid)throw new Error("UID wajib diisi");if(uid===actor&&(changes.active===false||changes.role==="student"))throw new Error("Admin tidak dapat menonaktifkan atau menurunkan role akunnya sendiri");const allowed:Record<string,unknown>={};if(typeof changes.active==="boolean")allowed.active=changes.active;if(changes.role==="admin"||changes.role==="student")allowed.role=changes.role;if(password){if(String(password).length<6)throw new Error("Password minimal 6 karakter");await adminAuth().updateUser(uid,{password:String(password)})}if(Object.keys(allowed).length)await adminDb().collection("users").doc(uid).update(allowed);if(typeof allowed.active==="boolean")await adminAuth().updateUser(uid,{disabled:!allowed.active});return NextResponse.json({ok:true})}catch(e){return fail(e)}}
export async function DELETE(req:NextRequest){try{const actor=await authorize(req);const {uid}=await req.json();if(!uid)throw new Error("UID wajib diisi");if(uid===actor)throw new Error("Admin tidak dapat menghapus akunnya sendiri");await Promise.all([adminAuth().deleteUser(uid),adminDb().collection("users").doc(uid).delete(),adminDb().collection("academicData").doc(uid).delete()]);return NextResponse.json({ok:true})}catch(e){return fail(e)}}
